### ISSUE TITLE
get_save_filename_ext() doesn't prevent the user from saving as a no extension file

### ISSUE THREAD

**Issue by chenxi050402** [time-killer-games/libdlgmod#3]
When the user removed the extension from the filename, it just saves it as that name and doesn't add the extension.

**Comment by time-killer-games** [comment]
Is this a problem on all platforms, or just windows? I can add a fallback extension that it automatically adds when none is provided, relative to the first file filter item, but if this is a problem on Linux, I won't be able to set it to the current format selected in the dropdown because with the current API used there is no way to detect that, so it will have to be the first format mentioned in the entire file filter list to remain cross-platform, is that ok? This behavior can also be programmed on your end, in GML by modifying the returned file extension using filename_change_ext, but I can create a function that when set to true will make it do this for the save dialogs automatically, not everyone will want this behavior and so I will make it optional.

**Comment by chenxi050402** [comment]
It's only on Windows.
I'm not sure adding that will fix the issue because when I add the extension after saving, if the user types the same filename as the existing one but without the extension, it won't prompt for overwrite.
The native function is fine and it looked the same on Windows.

**Comment by time-killer-games** [comment]
Cool, I'll see what i can do! I'll close this issue after I've both fixed it and you were able to verify that with a comment here. :)

**Comment by time-killer-games** [comment]
@chenxi050402 Hi, I got involved with some contract work which has put this off quite a bit, but I'm just letting you know I haven't forgotten your request and still intend to fix it. Thank you for your patience!

**Comment by time-killer-games** [comment]
@chenxi050402 I've made some improvements, which it isn't precisely what you wanted, it's definitely a lot closer to it.

Please replace your existing dll's with the ones now available at this link:
https://github.com/time-killer-games/libdlgmod/releases/tag/v1.0.0.0
